### ISSUE TITLE
Support for multiple executables in bundle

### ISSUE THREAD

**Issue by kaicherry** [trojanfoe/xcodedevtools#1]
Andy, I'm not a python guy, so to you I ask: is it possible to extend this to do this task on *all* of the executables in the MacOS folder? I have found that on mojave, it seems *all* executables now need to be in MacOS; the script is only targeting the executable specified as the build executable by Xcode.

Concrete example - app needs to bundle command line tools (in or out of sandbox, case is the same) and those tools link to the dylibs. I am finding the "helpers" are still link inked to /usr/local and /opt/local.

More an enhancement than issue i suppose :)

**Comment by trojanfoe** [comment]
Hello sorry for the late reply but I did not see your issue.

I would have thought it would probably work out of the box on multiple executables, but you would need to attach the script to every project that produces an executable.  There would be duplication of work, but that’s about it.  As Xcode only supplies the name of one executable via environment variables, I don’t see any other way of doing it (however it’s been a while since I used Xcode at all).
